schema = 3

[mod]
  [mod."github.com/klauspost/compress"]
    version = "v1.17.7"
    hash = "sha256-UkW+tAFEZYj067z9gXDQjQx0dCF8noCn5OSw/APh4oo="
  [mod."github.com/nats-io/nats.go"]
    version = "v1.34.0"
    hash = "sha256-Vjy5KVOJH+lVJ8tZwvwFAKWI8qZqpAh2gtu8+rp2aNo="
  [mod."github.com/nats-io/nkeys"]
    version = "v0.4.7"
    hash = "sha256-ui/vSa2TGe6Pe2aAzitBa1Pd2vKgTMuHoBhYYy2p6Rw="
  [mod."github.com/nats-io/nuid"]
    version = "v1.0.1"
    hash = "sha256-7wddxVz3hnFg/Pf+61+MtQJJL/l8EaC8brHoNsmD64c="
  [mod."golang.org/x/crypto"]
    version = "v0.21.0"
    hash = "sha256-Z4k1LvFh4Jai7HUe6TTuXSG3VnuiRpMwdARIdZZqSYk="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
